### ISSUE TITLE
Documentation improvements for navigation configuration section

### ISSUE THREAD

**Issue by kwiatekus** [SAP/luigi#101]
**Description**

We document how to pass node params via link manager. But we don't describe how to read them using luigi client. Its hard to guess that without going through the code of the sample application.

**Comment by bszwarc** [comment]
Within this task, we have added descriptions on node parameters and path parameters, and reorganised the document. 
It should be now reviewed and the PR can be later on merged so that the changes are there. 
Additionally, there might have been some changes on the micro front-end documentation side (API doc)?
