### ISSUE TITLE
ProductSwitcher scrolling on mobile not ideal

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#1018]
When you have e.g. 10 items in product switcher you will not see the last item until you try to scroll 2-3 times.
Tested on iPhone/Safari.

**Comment by ndricimrr** [comment]
The bug seems to be related with the major switch to fundamental styles. The added wrapper element
`<div class="fd-product-switch__body fd-product-switch__body--mobile"> `
seems to have caused the issue. This was fixed in @marynaKhromova  's switch-to-fundamental-styles thus am closing this issue as the bug is resolved.
