### ISSUE TITLE
Investigate lerna alternatives

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#1105]
* https://nx.dev/web/getting-started/what-is-nx
* https://rushjs.io/
* https://bit.dev/ (component)
* https://github.com/boltpkg/bolt (yarn)

**Comment by zarkosimic** [comment]
**NX**
used for full-stack applications, a specific installation(project structure - separated folders for frontend, backend, libs, API) what can take more time to set up. If not based on any of frameworks(Angular, React) then uses TypeScript files, work well with Cypress, have dependency graph, good for scaling and managing hundreds or even thousands of packages.

**Rush.js**
Pros :
- A single NPM install : in one step installs all the dependencies for all projects into a common folder.
- Automatic local linking : Inside a Rush repo, all projects are automatically symlinked to each other.
- Fast builds : Rush detects dependency graph and builds projects in the right order. If two packages don’t directly depend on each other, Rush parallelizes their build as separate NodeJS processes.
- Bulk publishing : When it’s time to do a release, Rush can detect which packages have changes, automatically bump all the appropriate version numbers, and run `npm publish` in each folder.
- Changelog tracking : Whenever a PR is created, it requires from developers to provide a major/minor/patch log entry for the affected projects. During publishing, these changes will be automatically aggregated into a nicely formatted CHANGELOG.md file.
- No phantom dependencies(possible will not work with Travis CI)

Cons : 
- Potential problem during installation(npm - account permissions) and with npm in general(didn’t work well with some versions).
- Avoid certain commands in a Rush repo(`npm run`, `npm install`, `npm update`, `npm link`).
- If you suspect your install is corrupted… then needed to force a full reinstall of all package.

**Bit**
growingly popular tool that makes it easier to share, collaborate and sync code between projects, with zero refactoring or overhead. Bit is open-source and plays with Git and NPM to help team scale code-sharing and build faster together. Even though it’s based on components, its abstraction and unique features make it a very powerful tool for handling large multi-package Monorepos with NPM.

Pros :
- 0 refactoring to the repository. It takes minutes from 0 to publishing 100 packages from your existing library. Try it.
- Scalable code-sharing without the overhead.
- Great visual discoverability for components.
- Bit automatically manages all dependencies in the repo, including changes to component dependencies, and updates all components as required. No different package.json files to maintain or update.
- Change management can be done via PRs to the repo, or via issuing component updates from any other repository by importing a component, making changes and issuing an update to the original repository.
- Automated updates on releases (Bit in CI/CD).

Cons :
- Extension system is coming up. Until then, you might have to modify build/test environments a bit for different tools you work with.
- Install as packages via Bit’s registry with the NPN/Yarn clients (your choice). Not supporting NPM’s registry.
- All the hub’s features (search, playground, npm install) require that you host code in the hub (like GitHub and NPM). There’s no vendor locking (Bit is distributed like Git and can be set up on any server).

Since Bit is abstract enough to work in any architecture, it can work hand-in-hand with a Lerna in a monorepo to provide the above advantages on top. For example, Lerna can be used to manage the core packages while Bit can be used to share all smaller components. Bit also provides discoverability on top of Lerna, and reduces the amount of refactoring and maintenance needed.

**Bolt**
Bolt and Lerna were both created by the same folks. Bolt is meant to be even more of a "project" based, and is actually kind of a wrapper around Yarn and Yarn Workspaces. It also locks the dependencies of the shared packages. Meaning, a single version of React, or React Router, etc is installed across all of the packages in the megarepo.

In a bolt megarepo, unlike lerna, when we add a project to a package, it is also automatically added to the top level package.json. This makes installs a bit quicker and easier as we won't ever have forked dependencies like we can in Lerna.

**Lerna**

Pros : 
- Mature and plenty of tutorials around the web.
- Version all packages separately or in a single line.
- Link dependencies in the project with lerna bootstrap.
- Automation for task execution for all packages in the repo.
- Lerna publish publishes all updates to NPM.

Cons : 
- Heavy refactoring for the repository. A lot of initial overhead.
- Maintenance overhead grows with different package.json and environments for every package.
- Discoverability for packages relies on NPM/library's docs.
- PRs can only be made in the repo, and it can be hard to onboard new developers into the repo, which in turn impairs adoption of packages.

P.S. Interesting [article](https://doppelmutzi.github.io/monorepo-lerna-yarn-workspaces/)

_NPM Trends_ : 

![image](https://user-images.githubusercontent.com/42171300/76293676-c7db6880-62b1-11ea-8a5d-591b8dd07155.png)

![image](https://user-images.githubusercontent.com/42171300/76293701-d1fd6700-62b1-11ea-91a6-9dea13a63cd9.png)
