### ISSUE TITLE
Context switcher disappearing when removing local storage

### ISSUE THREAD

**Issue by ndricimrr** [SAP/luigi#1382]
How to reproduce: 
- Try to remove local storage and switch to another mf. Context Switcher then dissapears

**Comment by maxmarkus** [comment]
Why would someone modify the localStorage and remove the `luigi.auth` object, which leads to an intermediate wrong state, since `loggedIn` flag is null and not all parts are reacting on that properly, it seems.

I guess we talked about this a long time ago already and agreed its dev misbehaviour, which he should know that there might break something if you clear the configured `auth.storageType`.

@hardl can have a look at this again and verify if there is some todo.
