### ISSUE TITLE
Replace insensitive terms with inclusive language

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#1651]
Whole repository, documents and code.

Due date: Dec 31st, 2020

For further information, please have a look at
•	this Jam Group https://jam4.sapjam.com/groups/fpVjPTHoZVTjFIbqxZSK6s/overview_page/slC3Df1qamKevuJmaoKNRO

**Comment by alexandra-simeonova** [comment]
The terms whitelist/blacklist and master/slave need to be changed according to SAP guidelines.

Regarding whitelist, we use it once in docs which should be fixed with PR #1771

Regarding master (e.g. master branch in Github), GitHub plans to release tools in the future to make the migration to the new term easier: https://github.com/github/renaming 

Therefore, it might be best to wait for the official Github tools before updating the term. 

See point 13 in the Jam group FAQ for more info: https://jam4.sapjam.com/groups/fpVjPTHoZVTjFIbqxZSK6s/documents/GQAbbJ2bjGtPTogfhe2NkN/slide_viewer?_lightbox=true&label=Slide+1

**Comment by alexandra-simeonova** [comment]
Comment on the current status of GitHub's `master` branch: https://jam4.sapjam.com/feed/item/jcKhjWeRTfxrhB4iCLPLY7?anchor_feed=true

**Comment by JohannesDoberer** [comment]
We will go with the current setup.
