### ISSUE TITLE
Nested Microfrontends

### ISSUE THREAD

**Issue by alexanderbartels** [SAP/luigi#1705]
**Description**

I try to place a microfrontend within another microfrontend. But it looks like this is not possible with Luigi. I have found 3 different Layout Options:
* Microfrontends takes all the space, except for the luigi navigation, header, footer, etc.
* Split Screen: i can place two microfrontends next to each other (but not nested)
* Modals: I can open as much microfrontends as i like in a modal, but these are added to the end of the body.

I tried myself to place an iframe within my Microfrontend to load another. But with this approach the luigi client doesn't work anymore, so i'm not able to call `#navigate()` and stuff like that. 

**Reasons**

I want to build a landing page where i have mostly static content (Microfrontend 1) and i have some interactive widget (Microfrontend 2) which needs to placed within Microfrontend 1 to match the design specs. See attached Image for details on my target layout i try to achieve.

**Attachments**

![microfrontend-wireframe](https://user-images.githubusercontent.com/522396/99115453-b2fa6600-25f2-11eb-809b-2aca67d7f9c0.png)

Is it possible to achieve such a layout with Luigi ? 

Thanks in advance!

**Comment by hardl** [comment]
Hi,

in general this will soon be possible with the release of web component based micro frontends.
See epic https://github.com/SAP/luigi/issues/1093 and corresponding PR https://github.com/SAP/luigi/pull/1657

This will not include support for iframed micro frontends though, at least with its initial release, because it is quite tricky, since iframes are blackboxes for luigi core... however I am aware of some people working on a "luigi client proxy", allowing exactly what you have described in your manual approach. So the nesting micro frontend would forward calls from the nested one to luigi core and vice versa.

Best regards


P.S.: Please reopen, if it needs further discussion, or visit us in our public slack workspace ;)
