### ISSUE TITLE
Silent Renew for OIDC is not working

### ISSUE THREAD

**Issue by valentinvieriu** [SAP/luigi#1824]
**Description**

The silent renew page (https://github.com/SAP/luigi/blob/master/plugins/auth/public/auth-oidc/silent-callback.html) is misconfigured. Following the documentation https://docs.luigi-project.io/docs/auth-oidc does not produce any `/assets/auth-oidc/oidc-client.min.js` file.
The `node_modules/@luigi-project/plugin-auth-oidc contain` does not contain such file

**Expected result**
Silent redirectRenew should. work

**Actual result**

The silent renew page is not working

**Steps to reproduce**

Follow the steps from https://docs.luigi-project.io/docs/auth-oidc and have `automaticSilentRenew: true`

**Comment by valentinvieriu** [comment]
I assume this is because this is ignored in the .gitignored file (`plugins/auth/public/auth-oidc/.gitignore`) and this is not released to npm

**Comment by legteodav** [comment]
Hi @valentinvieriu.

Actually it is not a bug, it is a problem in the documentation. 
The file oidc-client.min.js it **should not be inside** our package plugin-auth-oidc (it is a third lib party).
We need to correct the documentation; in order to make it work, you would need to import library:

npm i -save-dev copy-webpack-plugin

And you would need to add this config in the webapck.config.json 

`
 plugins: [
        new CopyWebpackPlugin({
            patterns: [
                {
                    from: 'node_modules/@luigi-project/plugin-auth-oidc/plugin.js',
                    to: 'assets/auth-oidc'
                },
                {
                    from: 'node_modules/@luigi-project/plugin-auth-oidc/plugin-ie11.js',
                    to: 'assets/auth-oidc'
                },
                {
                    from: 'node_modules/@luigi-project/plugin-auth-oidc/silent-callback.html',
                    to: 'assets/auth-oidc'
                },
                {
                    from: 'node_modules/oidc-client/dist/oidc-client.min.js',
                    to: 'assets/auth-oidc'
                }
            ]
        })
    ]
`

let me know if you have any issue.

Cheers
Davide
