### ISSUE TITLE
Statistics for e2e app

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#2174]
We have no statistics how many test coverage we have for our e2e test app.
-> show statistics for e2e test coverage

Ideal we also can combine statistics of unit and e2e test coverage.
-> investigate if the combination of both is possible.

**Comment by rafalgamon** [comment]
All the logic that generates the report is ready.
The problem is that the stats are only generated for the e2e folder and not for the core. From what I was able to find on the internet, this solution can be in the files that are includes and excludes in the `nyc` configuration. But I try it and still I don't have any working solution.

**Comment by hardl** [comment]
de-prioritized, maybe can be revisited later, closing for now
