### ISSUE TITLE
Refactoring - convert .html file to .svelte file (/core/src/navigation/)

### ISSUE THREAD

**Issue by stanleychh** [SAP/luigi#2260]
Issue: According to this [PR](https://github.com/SAP/luigi/pull/2236/files#diff-2b5d04d984372d11919588635e3dd35851ee7aba20af0065721e057a43d78c68), it seems missing the prettier setup for Svelte syntax. 

For improving better syntax readability, convert /core/src/navigation/*.html files to .svelte files.

TO DO: introduce [prettier-plugin-svelte](https://www.npmjs.com/package/prettier-plugin-svelte) to project. Or any other package/plugin to make it work.

VS Code settings: https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode

**Comment by ndricimrr** [comment]
I believe we've already had a small discussion in the past with our svelte files being in `.html` and not `.svelte`. I don't remember why it was chosen to be html in the very beginning, so that could be a good topic for tomorrows after scrum. 
 
Regarding prettier, I think the most simple and easy solution is to first convert html files to `.svelte` and then add a prettier config for svelte files as you suggested. However, need to discuss it first if that can have any implications on functionality.
