### ISSUE TITLE
Angular script does not work out of the box

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#2310]
Our current setup to luigify an angular app does not work out of the box.
https://docs.luigi-project.io/docs/application-setup?section=application-setup-for-angular

Please check also other examples (if there are issues as well; fix it or create new issues)

**Comment by JenniferStamm** [comment]
I've also noticed that the [Angular setup script installs an outdated fundamental-styles version](https://github.com/SAP/luigi/blob/5199a4dcf2a05c22214dbdf9c98e174a4db0b7dc/scripts/setup/angular.sh#L16) (installs fundamental-styles@0.11.0, current is fundamental-styles@0.21.01). The no-framework setup doesn't reference a specific version. Maybe you want to take a look at that while working on this?

If not, I can also open a separate issue.

**Comment by viktorsperling** [comment]
I'm on it:

- [X] Angular setup checked (step-by-step & `.sh` script)
- [X] Vue setup checked (step-by-step & `.sh` script)
- [X] React setup checked (step-by-step & `.sh` script)
- [X] OpenUI5 setup checked (step-by-step & `.sh` script)
- [X] No-Framework setup checked (step-by-step & `.sh` script)

These are my findings / changes:

1. For Angular, the latest fundamentals version is causing some issues, concerning the fonts for the embedded MFEs. A PR from @UlianaMunich should fix this. For the meanwhile, I've added a workaround solving this. This should be removed later.
2. For OpenUI5, there is a command in the [step-by-step setup](https://docs.luigi-project.io/docs/application-setup?section=application-setup-for-vuejs), which is not executed for the `.sh` [script](https://github.com/SAP/luigi/blob/5199a4dcf2a05c22214dbdf9c98e174a4db0b7dc/scripts/setup/openui5.sh). @alexandra-simeonova maybe have a look at it? It's the `npm init -y` command. In both cases, it works fine.
3. For React, there is a issue with the basePath attribute of the react router. This is apparently a known issue and the #2646 PR should fix this. For both cases (`.sh`, step-by-step setup), no MFEs can be rendered by the resulting applications, due to this.
4. For Vue, there are significant differences between the commands of the [step-by-step setup ](https://docs.luigi-project.io/docs/application-setup?section=application-setup-for-vuejs) and the `.sh` [script](https://github.com/SAP/luigi/blob/5199a4dcf2a05c22214dbdf9c98e174a4db0b7dc/scripts/setup/vue.sh). Instead of fixing the issues I've found, I highly recommend to update the commands of the step-by-step setup, with the commands from the `.sh` script. This will solve all the problems sustainably. As of now, the result of the step-by-step setup is not working.
