### ISSUE TITLE
url "anchor" support for micro frontends

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#2433]
Allow the micro frontend to read and write the "abstract hash part" of the main url to leverage in-page navigation (e.g. scrolling).

Proposed solution:
* add functions `getAnchor` and `setAnchor` to luigi client api
* anchor is transfered via internal context
* anchor is only distributed to the "active" micro frontend defined by the route in the url, i.e. it behaves like `nodeParams`.

Note:
"abstract hash" means it is transparent which routing strategy is used. For path-based routing it is simply the hash part of the location, e.g.
`http://localhost:4100/path/to/mfe#anchor`
For hash routing, it is not the full hash, but only the hash part of the hash, e.g.
`http://localhost:4100/#/path/to/mfe#anchor`

**Comment by AlexandarNaydenov** [comment]
@stanleychh  @hardl 
Is it possible to add a functionality like `withoutSync()` for setAnchor()?
Because I want to add the "hash" to the url without reloading the page. 
Same behavior like using: `LuigiClient.linkManager().withoutSync().navigate("#something")`

**Comment by AlexandarNaydenov** [comment]
Hi @ndricimrr! 
Sorry for the delay!

We are using SAP UI5 frontend, but I think you are right. The request mapping is receiving a new event on configChange and it is reloading the page. 
Is it possible to create a feature request for the `setAnchor` functionality to have a parameter or something similar that says not to do configChange. (similar behavior like `withoutSync on the navigate`) ?
Because now I need to use something like : `LuigiClient.linkManager().withoutSync().navigate("#something")` to not fire a new event, which is not very beautiful.

**Comment by ndricimrr** [comment]
@AlexandarNaydenov Hi, sure, we'll look into this and come up with a response/PR as needed.
