### ISSUE TITLE
Update angular support lib to angular v16

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#2926]
Update to angular v16

**Comment by JohannesDoberer** [comment]
Also check testing-utilities

**Comment by JenniferStamm** [comment]
any update on whether you'll upgrade until eoy?

**Comment by JohannesDoberer** [comment]
Hey Jennifer,
before we update to angular v15 we need to release Luigi 2.0.
Currently we are preparing Luigi v2.
I can't make a promise but we are trying to release it by end of the year.
I'll keep you updated.

**Comment by JenniferStamm** [comment]
@JohannesDoberer cool, sounds great 🙂

**Comment by JenniferStamm** [comment]
@JohannesDoberer We started the upgrade today as planned. As expected, this is blocking us from upgrading :

`Package "@luigi-project/client-support-angular" has an incompatible peer dependency to "@angular/core" (requires "^11.0.0 || ^12.0.0 || ^13.0.0" (extended), would install "15.0.4").`

We'd really like to upgrade due to the project's other dependencies that now require Angular 15. Any news on the v2 release?

**Comment by JohannesDoberer** [comment]
Clarified in a slack conversation.

**Comment by aaasarthak** [comment]
Hi, is there any timeline for v16 support from Luigi?  We would like to update our application.

**Comment by hardl** [comment]
Hi @aaasarthak, probably this week, latest next week.
BR
