### ISSUE TITLE
Evaluate screenster.io  for ui tests for luigi

### ISSUE THREAD

**Issue by kwiatekus** [SAP/luigi#293]
https://screenster.io

...or find an even better tool ;)

**Comment by ndricimrr** [comment]
**Screenster**

**_Description_** 
Creates test through dashboard, no need to write code (main feature) 

**_Pricing_** 
- _Free plan_ = 100 (local) / 50 (cloud) tests per month , max 1 user 
- _Basic Plan_ =   25$/month ,  600 (local) – 200 (cloud) test runs per month, max users 5

_**Speed**_ 
- Simple Luigi test suite with 14 simple steps :
- ![image.png](https://images.zenhubusercontent.com/5ddce54970febb0001f9c812/8a61f88b-7c5e-457a-9f0d-51fc19386f71)
- Result : ![image.png](https://images.zenhubusercontent.com/5ddce54970febb0001f9c812/60b3e1a5-e898-426e-b49a-a6570bf8cfe7)
Test took 2 min 30 secs, because :  - “This run will create a full-sized baseline for this browser. The **execution might take some time** because Screenster will assess page structure, analyze your actions and prepare interactive screenshots for each step.”

_**Local testing**_ 
- [Only](https://screenster.io/documentation/local-installation/) **Windows** supported :/ 

_**Additional**_
- Sharp price decrease from [100$](https://web.archive.org/web/20160501175526/https://screenster.io/pricing/) to [25$](https://screenster.io/pricing/) 
- Only 1 question on [StackOverflow](https://stackoverflow.com/search?q=screenster.io)


**_Other Alternatives_**
- Protractor
- Open source 
- Used only with angular
- Generous community support , 10 300+ related questions on [StackOverflow](https://stackoverflow.com/questions/tagged/protractor)
