### ISSUE TITLE
Copy-webpack-plugin cannot copy luigi.svelte.map.js file

### ISSUE THREAD

**Issue by MadinaN12** [SAP/luigi#2938]
**Description**

GitHub DependaBot alerted about glob-parent npm package vulnerability and I updated copy-webpack-plugin from version 5.1.2 to latest 11.0.0 (to update glob-parent to version 6.0.1 because glob-parent package is a dependency of copy-webpack-plugin).
I use the 1.24.0 version of Luigi.
![image](https://user-images.githubusercontent.com/74180306/196938350-fc4a5a54-9376-40c9-b115-7c1c2fc8813d.png)

But now on build I catch this error with luigi-core/luigi.svelte.map.js file. (see screenshot)

![image (1)](https://user-images.githubusercontent.com/74180306/196938692-3ca06cab-08e0-42ea-bf4e-30d980b37ce9.png)

My package.json:

```{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "engines": {
    "yarn": "1.x"
  },
  "resolutions": {
    "tough-cookie": "4.0.0",
    "css-what": "^6.0.1",
    "nth-check": "^2.0.1"
  },
  "scripts": {
    "eslint": "eslint --ext .js src/",
    "buildConfig": "webpack --config webpack.config.js",
    "start": "node scripts/start.js",
    "test": "node scripts/test.js",
    "test:ci": "yarn test --silent --coverage --coverageDirectory=output/coverage/jest --maxWorkers=70% --maxConcurrency=3",
    "test:coverage": "yarn test --watchAll=false --coverage",
    "test:precommit": "yarn test --watchAll=false --silent",
    "build": "node scripts/build.js",
    "buildWithConfig": "yarn buildConfig && yarn build && mv build dist",
    "prepare": "husky install",
    "jest-coverage": "yarn jest --coverage"
  },
  "dependencies": {
    "@luigi-project/client": "^1.17.0",
    "@luigi-project/core": "^1.17.0",
    "@luigi-project/plugin-auth-oidc": "^1.20.1",
    "@reduxjs/toolkit": "^1.8.1",
    "@sap-theming/theming-base-content": "^11.1.34",
    "@testing-library/dom": "^7.21.4",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^14.1.0",
    "@ui5/webcomponents": "1.5.0",
    "@ui5/webcomponents-fiori": "1.5.0",
    "@ui5/webcomponents-react": "0.26.0",
    "deepdash": "^5.3.9",
    "eslint-plugin-sonarjs": "^0.15.0",
    "jira2md": "2.1.0",
    "moment": "^2.29.1",
    "prop-types": "^15.7.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-redux": "^8.0.2",
    "react-router-dom": "^5.3.0",
    "react-scripts": "5.0.1",
    "react-scroll": "^1.8.4",
    "react-simple-image-viewer": "1.1.1",
    "styled-components": "^5.3.1",
    "web-vitals": "^1.0.1"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!(@ui5|lit-html)).*\\.js$"
    ],
    "coverageReporters": [
      "clover",
      "json",
      "lcov",
      "text",
      "cobertura"
    ]
  },
  "jestSonar": {
    "sonar56x": true,
    "reportPath": "./output",
    "reportFile": "sonar-report.xml",
    "indent": 4
  },
  "babel": {
    "presets": [
      "@babel/preset-react"
    ],
    "plugins": [
      "@babel/plugin-syntax-dynamic-import"
    ]
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.16.5",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.3",
    "commit-message-validator": "^1.0.2",
    "copy-webpack-plugin": "^11.0.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "husky": "^8.0.0",
    "jest": "^28.1.0",
    "jest-circus": "^28.1.0",
    "jest-environment-jsdom": "^28.1.0",
    "jest-resolve": "^28.1.0",
    "jest-sonar-reporter": "^2.0.0",
    "jest-watch-typeahead": "^1.1.0",
    "lint-staged": "^13.0.3",
    "oidc-client": "^1.11.5",
    "prettier": "2.6.2",
    "resize-observer-polyfill": "^1.5.1",
    "string.prototype.replaceall": "^1.0.6",
    "webpack-cli": "^4.10.0"
  },
  "lint-staged": {
    "*.{js,ts,tsx}": [
      "eslint --quiet --cache --fix"
    ],
    "*.{json,js,ts,jsx,tsx,html}": [
      "prettier --write"
    ]
  },
  "config": {
    "commit-message-validator": {
      "_comment": "pattern can be Regex string or array of Regex string",
      "pattern": "OBS-[0-9_]+[: ][ A-Z0-9_@./#&+-]{8,50}([a-zA-Z0-9_ ]{0,72})?$",
      "errorMessage": "COMMIT FAILED - Commit message has invalid format. Valid commit message example: OBS-123: REQUIRED COMMIT SUBJECT (8-50 symbols limit, uppercase) Optional commit body (72 symbols limit)"
    }
  }
}
```
How I copy Luigi core files with copy-webpack-plugin:

```new CopyWebpackPlugin(
        {
          patterns: [
            { context: 'public', to: 'index.html', from: 'index.html' },
            {
              from: 'node_modules/@luigi-project/core/**',
              to: './luigi-core',
            },
          ],
        },
        {
          ignore: ['.gitkeep', '**/.DS_Store', '**/Thumbs.db'],
          debug: 'warning',
        }
      ),
```
For build I used this [file](https://github.com/SAP/luigi/blob/master/core/examples/luigi-example-react/scripts/build.js)

**Comment by ndricimrr** [comment]
Hi @MadinaN12 ,
This seems like an issue that has to do with the Webpack configurations and not a specific Luigi core logic internally. Note that the Luigi-React example provided should function as a starting point simple example and bundle config and other changes might be needed as you update the webpack related package versions. The same should apply if you are not using webpack but another bundler to do the same task.

Regarding the specific issue I think we might have a solution for that:

The `luigi.svelte.map.js` is a source-map file that we generate to assist in development mode and debugging luigi internal issues. 

It seems in your example that when updating the **copy-webpack** plugin, Terser seems to fail to minify our source-map when such minification would previously be ignored for source map type files. 

I believe this is because the **luigi.svelte.map.js** is seen as a Javascript file when in fact it isn't one and **Terser** tries to minify something that it shouldn't. We'll look into options such as renaming our source map file to  **luigi.svelte.js.map** instead and this issue should be resolved. Created an issue to track this [here](https://github.com/SAP/luigi/issues/2965). 

**Provided solution:**
In the meantime here are some ways to circumvent this issue from happening:
Use the [exclude](https://webpack.js.org/plugins/terser-webpack-plugin/#exclude) option from Terser plugin to exclude this source map from being minified by Terser. 

Example below:

```
 optimization: {
      minimize: true,
      minimizer: [
        // This is only used in production mode
        new TerserPlugin({
              exclude: /\.svelte\.map\.js$/,
              terserOptions: { ... }
             ...
        })
      ]
}
```

In addition it seems like in the latest **copy-webpack-plugin** version the copying of the index.html is not required anymore or seen as duplicate. You may remove the  `{ context: 'public', to: 'index.html', from: 'index.html' },` line on your **copy-webpack-plugin** config if that causes issues for you. 

Let us know if this solves your issue

**Comment by ndricimrr** [comment]
Currently not in progress anymore. Closing this as solution offered. 
Feel free to re-open it needed.
