### ISSUE TITLE
Fiddle product switcher not working

### ISSUE THREAD

**Issue by alexandra-simeonova** [SAP/luigi#3046]
**Description**

When you click on the items in the [Fiddle](https://fiddle.luigi-project.io/#/home/overview) product switcher, the links don't open.

**Expected result**

The links open in a new page. 

**Actual result**

The links don't open.

**Steps to reproduce**

Go to https://fiddle.luigi-project.io and click on the items on the top right.

**Comment by ndricimrr** [comment]
Was broken on **22.08.2022** since the nightly release:
_21.08.2022_ = [1.24.1-dev.202208212328](https://www.npmjs.com/package/@luigi-project/core/v/1.24.1-dev.202208212328) does work, whereas nightly release:
 _22.08.2022_ = [1.24.1-dev.202208222331](https://www.npmjs.com/package/@luigi-project/core/v/1.24.1-dev.202208222331) **doesn't.**

The PR that broke it is https://github.com/SAP/luigi/pull/2804 which touches externalLink where the error is showing.

**Comment by ndricimrr** [comment]
This exact issue was fixed in **Oct 7** [on this commit ](https://github.com/SAP/luigi/commit/c43aa61e9f5cedf2b37285ca0bb50e6beea77724)

Need to make a **release** and update fiddle version accordingly afterwards.

**Comment by ndricimrr** [comment]
This was resolved with 1.26.0 release
