### ISSUE TITLE
Splitview Mf won't be resized if drawer overlap is false

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#3150]
Given:
splitview + drawer *overlap=false* does not resize the splitview. 
Only the "main" microfrontend will be resized when drawer will be opened.

Expected:
Both microfrontends (main and splitview) will be resized.

**Comment by ndricimrr** [comment]
@somabagyinszky7 , will have to check the relevancy here, but in the meanwhile, can suggest another issue. 
#3292

**Comment by somabagyinszky7** [comment]
Hi @ndricimrr,
Thank you for recommending #3292!
I can work on that!

**Comment by somabagyinszky7** [comment]
Hi @ndricimrr,
I would be happy to work on this.

**Comment by JohannesDoberer** [comment]
Hey @somabagyinszky7,
feel free to work on this issue :). 
Sorry for late response, I didn't see it.
Cheers

**Comment by somabagyinszky7** [comment]
Hi @JohannesDoberer, hi @ndricimrr,
I would like to have a more design-oriented question.
I found the underlying reason for this bug.
It happens because the function `getCurrentMicrofrontendIframe()` in `iframe-helpers.js` only returns the iframe with type `main` instead of returning the `main` and `split-view` iframes. Thus only the `main` iframe gets resized.

My question is the following:
Do you think that in the future you would implement, or do you already have other use cases / micro frontend arrangements that would require the resizing of multiple iframes at the same time?
* If yes, I would propose that the `getCurrentMicrofrontendIframe()` should return an array of iframes that need to be resized. This would make it a more robust/general solution and would be easier to extend in the future.
* If not, or if it's a bad idea for some reason I cannot yet see, my alternative solution would be to handle the split-view as a special case and leave the rest as is.

The general idea:


What do you think?
Thank you,
Soma

**Comment by hardl** [comment]
Hi @somabagyinszky7, thank you very much for your question.
Changing existing API is always sth that should be avoided because it is a breaking change and customers have a bad upgrade experience. And this helper function is exposed to core API.
I would rather propose not to use getCurrentMicrofrontendIframe() at all for this functionality but rather do the sizing operations on the container elements only, i.e. iframeContainer. Looking at the code and the resulting html structure, i'm afraid that everything that should be resized on drawer overlap must be defined somehow, since there is no single parent container element. In addition, I found at least 2 other components that are currently not resized but should: Tabnav and Breadcrumbs. Probably the best idea is to mark all of them with a dedicated attribute and then use querySelectorAll in App.svelte:resizeMicrofrontendIframe and iterate over all of them and setting the width.

**Comment by somabagyinszky7** [comment]
Hi @hardl,
Thank you for your reply! Makes sense. I will look into this and come up with a pull request in the coming days.
I will also keep in mind the bit about changing the API for the future.
