### ISSUE TITLE
Refactor ts declaration for context in luigi-client

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#3418]
Currently we have a context ts declaration where everything is stored.
It makes more sense to split it up like:

```
export declare interface Context{
nodeParams?: NodeParams;
  pathParams?: PathParams;
...
}
```
```
export declare interface MetaContext{
internal?: {
    userSettings?: getUserSettings;
  };
...
}
```

Also update client-support-angular lib.

**Comment by JohannesDoberer** [comment]
After discussion with PO the interfaces should look like this:
```
export declare interface Context {
  context?: { parentNavigationContext?: string[] };
  [key: string]: any;
}

export declare interface InternalContext {
  authData?: AuthData;
  context?: Context
  internal?: {
    userSettings?: getUserSettings;
  };
  nodeParams?: NodeParams;
  pathParams?: PathParams;
  anchor?: string;
}
```
That means, internally where we have previously developed against Context, then use InternalContext
AND: leave public interface functions on Context, e.g. addInitListener, addContextListener, getEventData, getContext

**Comment by walmazacn** [comment]
I did some tests for case when you expect original 'Context' ('InternalContext' after changes), but new 'Context' is provided. As long as you try to get a value from not existing property you will get `undefined` - like here:
`currentContext.internal`

But in case you want to get some nested property then "Uncaught TypeError" will occur - like here:
`currentContext.internal.userSettings`

That's why we may think of introducing separate contexts as a breaking change

**Comment by walmazacn** [comment]
Btw, why do we extend `internal` property with non existing props for current context in 'lifecycleManager'?

- `this.currentContext.internal.isNavigateBack`
- `this.currentContext.internal.activeFeatureToggleList`
- `this.currentContext.internal.clientPermissions`
- `this.currentContext.internal.anchor`
