### ISSUE TITLE
Investigate why backwards compatibility tests are failing

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#3521]
**@luigi-project/client-support-angular** module will not be found in e2e test app

**Comment by JohannesDoberer** [comment]
Maybe it can be solved by #3510 or #3321

**Comment by ndricimrr** [comment]
They were failing because we used to delete content of `node_modules/@luigi-project/*` and then symlink it for the **Compatibility Tests** below. 

Since `@luigi-project/client-support-angular` was integrated recently into the e2e-test-application, the symlinking was not added causing `client-support-angular` to be missing. Should be solved in #3527. 

https://github.com/SAP/luigi/blob/03296864947d5feb0a6301af03b743641d64db41/scripts/testCompatibility.sh#L194-L205

**Comment by ndricimrr** [comment]
Resolved in #3527
