### ISSUE TITLE
Dynamic sizing of dialog based on content 

### ISSUE THREAD

**Issue by Happyjump** [SAP/luigi#3543]
**Description**

The size of a dialog should adapt to the content to prevent scrolling (dialog too small) or unnecessary whitespace (dialog too large) or adapt to content dynamically if eg form field are added or removed based on user input 

**Reasons**

Especially in use cases where form fields are added / removed based on user input a fixed dialog size leads to either scrollbars (if dialog is too small ) or unneccessary whitespace (if dialog is too large).

**Attachments**

In this example the 
"Vault Credential Store (optional):" formfield is available/not available based on different users 

Unnessessary Whitespace
![image](https://github.com/SAP/luigi/assets/31856793/c84017d9-a018-49a7-bcb3-caf8730fbe11)

Scrollbar
![image](https://github.com/SAP/luigi/assets/31856793/df357270-0862-470a-a520-31582e4af98c)

**Comment by hardl** [comment]
Setting the modal size from within the micro frontend is already possible by executing e.g.
`LuigiClient.linkManager().updateModalSettings({width: '200px', height: '220px'})`.
Since Luigi core doesn't know anything about the rendering internals of an iframed micro frontend, especially when exactly everything is loaded and rendered and the mfe view has its "final" size, the calculation and adjustment should be handled  by the micro frontend code.
