### ISSUE TITLE
Error in our container tutorial

### ISSUE THREAD

**Issue by JohannesDoberer** [SAP/luigi#3669]
When you do all the steps of our [container tutorial](https://developers.sap.com/tutorials/luigi-container.html) you will see the following error when you open localhost:8080/index.html

```http://localhost:8080/resources/sap/m/manifest.json 404 (Not Found)```

In addition the ui5.yml in step 3 has wrong format (incorrect indentations) when you copy it to your local ui5.yml.

**Comment by smahati** [comment]
It seems like the manifest.json error is an issue with the template itself, I didn't want to spend more time on it because it seems like an error that is not causing a problem. I did see an issue with the Luigi container, it placed the microfronted below an empty <main></main> section making it look a bit strange but it works. I'll fix that if I find the issue.
