### ISSUE TITLE
Node refresh bug

### ISSUE THREAD

**Issue by hardl** [SAP/luigi#571]
**Description**

Some nodes, when click on it while active, dont reload microfrontend but remove it completely. This doesn't affect a stable release but current RC (12)

**Expected result**

microfrontend gets refreshed

**Actual result**

microfrontends gets lost

**Comment by jesusreal** [comment]
This bug was introduced on pre-release (v0.4.12-rc.2)[https://github.com/SAP/luigi/releases/tag/v0.4.12-rc.2]. Latest release (v0.4.11)[https://github.com/SAP/luigi/releases/tag/v0.4.11] does not have this bug.

**Comment by jesusreal** [comment]
Bug was generated on [this commit](https://github.com/SAP/luigi/commit/5149f965aa01ca915db6f88b2a4e5f486d4d21ec):

**Comment by jesusreal** [comment]
Bug only affects to hash routing, path routing is not affected.

**Comment by jesusreal** [comment]
[This event listener](https://github.com/sap/luigi/blob/master/core/src/utilities/helpers/routing-helpers.js#L101) should be added for path and hash routing but it was being added only for path routing. Additionally I needed to get the hash path instead of the url path, i.e., for hash routing I needed to extract the hash from the window location instead of calling `Routing.getModifiedPathname`.
