### ISSUE TITLE
Fix UI compatibility tests execution

### ISSUE THREAD

**Issue by jesusreal** [SAP/luigi#720]
Currently they are failing, we want to be able to use them again.

**Comment by maxmarkus** [comment]
Fixed in #750  by using `cy.getIframeBody()` only, which now relies on `.iframe()` command to wait for iframe body. Also gracefully behave on uncaught runtime errors.

For testing against versions same or older 0.5.4, it is recommended to either update it with the code from the linked PR, or using e2e:open which is a bit more precise and does not fail so often.
